server:
  port: 8099
spring:
  datasource:
    schema: classpath:schema.sql
    data: classpath:data.sql
    url: jdbc:h2:mem:test;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: root
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    database: h2
    show-sql: true
